# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         ElkM1-Control
version:      0.02
version_from: lib/ElkM1/Control.pm
installdirs:  site
requires:
    IO::Socket::INET:              1.27
    IO::Socket::SSL:               0.97

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
